In [3]:
pip install numpy
#conda intall numpy

SyntaxError: invalid syntax (10082630.py, line 1)

In [5]:
import numpy as np

In [21]:
lis=[2,3,4,5,6]
arr=np.array(lis)


In [17]:
type(arr)

numpy.ndarray

In [23]:
arr

array([2, 3, 4, 5, 6])

In [25]:
arr.shape

(5,)

In [33]:
l1=[1,2,3,2]
l2=[4,5,6,3]
l3=[7,8,9,3]
arr=np.array([l1,l2,l3])
arr

array([[1, 2, 3, 2],
       [4, 5, 6, 3],
       [7, 8, 9, 3]])

In [35]:
arr.shape

(3, 4)

In [41]:
arr.reshape(4,3)

array([[1, 2, 3],
       [2, 4, 5],
       [6, 3, 7],
       [8, 9, 3]])

In [43]:
#indexing

In [45]:
arr=np.array([2,3,4,5,6])
arr[2]

4

In [57]:
l1=[1,2,3,2]
l2=[4,5,6,3]
l3=[7,8,9,3]
arr=np.array([l1,l2,l3])
arr

array([[1, 2, 3, 2],
       [4, 5, 6, 3],
       [7, 8, 9, 3]])

In [63]:
arr[0:2,2:]

array([[3, 2],
       [6, 3]])

In [65]:
l1=[1,2,3,2]
l2=[4,5,6,3]
l3=[7,8,9,3]
arr=np.array([l1,l2,l3])
arr

array([[1, 2, 3, 2],
       [4, 5, 6, 3],
       [7, 8, 9, 3]])

In [71]:
arr=np.arange(0,4)
arr


array([0, 3, 6, 9])

In [73]:
arr=np.arange(0,10,step=3)
arr

array([0, 3, 6, 9])

In [77]:
np.linspace(1,10,50) #returns an array of evenly spaced values within the specified interval [start, stop]

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [79]:
#copy function and broadcasting
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
arr[3:]=100
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [85]:
arr1=arr
arr1[3:]=500
arr

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [87]:
arr1 # array is referenc type

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [89]:
arr2=arr.copy()
arr2[3:]=2000
arr1

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [91]:
arr2

array([   0,    1,    2, 2000, 2000, 2000, 2000, 2000, 2000, 2000])

In [93]:
#some conditions very useful in exploratory data analysis

In [96]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
val=3
arr[arr<val]

array([0, 1, 2])

In [100]:
arr<2

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [102]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [104]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
arr1=np.arange(0,10).reshape(2,5)

In [120]:
arr2=np.arange(0,10).reshape(2,5)

In [122]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [124]:
np.ones(4,dtype=float)

array([1., 1., 1., 1.])

In [126]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [128]:
#random distribution
np.random.rand(2,3)

array([[0.82164483, 0.80176433, 0.72426455],
       [0.61481138, 0.63028561, 0.50116471]])

In [134]:
arr=np.random.randn(2,3)
arr

array([[ 0.36082093,  1.19903768,  1.29778771],
       [ 0.15344967,  1.73357603, -0.00303473]])

In [132]:
arr

array([[-1.17073735,  0.80556175,  0.64272468],
       [ 0.32944719,  2.79493366,  0.57859804]])

In [138]:
arr=np.random.randint(0,100,8)
arr

array([12, 12,  2, 54, 29, 50, 38, 17])

In [140]:
arr=np.random.randint(0,100,8).reshape(2,4)
arr

array([[94,  2,  2, 46],
       [82, 99, 47, 68]])

In [149]:
np.random.random_sample((1,5))

array([[0.39798869, 0.74238336, 0.78886221, 0.74254196, 0.75111745]])